spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity

server:
  port: 8082

eureka:
  client:
    serviceUel:
      defaultZone: http://localhost:8761/eureka/

